### ISSUE TITLE
Create a SQL function to get links from one traffic signal px to another

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data_tools#21]
We frequently get data requests asking for traffic speed data between point A & point B.

We can use previous work developing https://github.com/CityofToronto/bdit_triprouter using [HERE data](https://github.com/CityofToronto/bdit_data-sources/tree/master/here#routing-with-traffic-data) to use `pgRouting` to route between two arbitrary points in our network in order to get directional links between those two points. 

the function would have the signature `here.get_links_btwn_px(px_start, px_end)` and would return a set of the `link_dir` between the two traffic signals

**Comment by chmnata** [comment]
Created function `here_gis.get_links_btwn_px(_px_start int, _px_end int)`, takes the start and end px, then return the link_dir between the two px. 
```
CREATE or REPLACE FUNCTION here_gis.get_links_btwn_px(_px_start int, _px_end int)
RETURNS TABLE (px_start int, px_end int, seq int, link_dir text)
AS $$
WITH lookup as (
    SELECT _px_start, _px_end, origin.node_id as source, dest.node_id as target
    FROM 
    here_gis.px_nodes origin
    , here_gis.px_nodes dest
	where _px_start = origin.px and _px_end = dest.px
)
, results as (SELECT * FROM
    lookup 
    cross join lateral pgr_dijkstra('SELECT id, source::int, target::int, length::int as cost from here.routing_streets_18_3', source::int, target::int)
)

SELECT _px_start, _px_end, seq, link_dir
from results
inner join here.routing_streets_18_3 on edge=id
order by _px_start, _px_end, seq
$$
LANGUAGE SQL STRICT STABLE;
```
