### ISSUE TITLE
Damage Report: Create template and automate populating property damage collision spreadsheet 

### ISSUE THREAD

**Issue by chmnata** [CityofToronto/bdit_data_tools#34]
The original step says: 

>Open the previous month's PROPERTY DAMAGE COLLISIONS.xlsx spreadsheet, save a new copy for the new month. Populate fields using the information sent over from Step 4.

But I think if the PROPERTY DAMAGE COLLISIONS.xlsx is just gonna have the same fields every time we might as well create a template and use that instead. It doesn't have to be an actual existing template xlsx but maybe a couple lines of code that will create the same file every time. Check if it is indeed the same fields everytime, I don't have access to the L drive to check :( 

- [x] Save spreadsheets from SRCC (Weekly Toronto City Property Report) into the L drive of the month

- [x] develop code that will create the same base fields for PROPERTY DAMAGE COLLISIONS.xlsx

- [x] populate fields using information sent from SRCC

**Comment by tankedman** [comment]
Functionality working, waiting for final fields/template confirmation from Racheal
