### ISSUE TITLE
Damage Report: Automate updating rawcollisiondata.accdb in Access 2007

### ISSUE THREAD

**Issue by chmnata** [CityofToronto/bdit_data_tools#35]
Investigate if this step can be automated
> Open the rawcollisiondata.accdb in Access 2007 then open the 'query damage to city property 2017-2018' in design view. Update the ACCDATE and SUBMIT DATE fields with dates ranging for the month in question.

Then Copy results table into the new PROPERTY DAMAGE COLLISIONS.xlsx spreadsheet.

**Comment by tankedman** [comment]
Completed features, closing
