### ISSUE TITLE
Format the website to look aesthetically pleasing

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data_tools#8]
Include some descriptive text of what this does, how it works, what format the data needs to come in, who to contact for info (load this piece from the config file so an email doesn't get committed to Github)

**Comment by chelsrosic** [comment]
Colour scheme and format inspo & ideas: 

Blue (city of toronto blue) and white: 
![image](https://user-images.githubusercontent.com/32607196/52238299-a97a9080-2899-11e9-917a-ac4b65929370.png)

(City of Toronto) blue with grey, white and black 
https://www.awwwards.com/sites/canatal
